search/models.py
from datetime import datetime
from project.book import db


class Book(db.Model):
    __tablename__ = "books"

    id = db.Column(db.Integer, primary_key=True)
    bookname = db.Column(db.String, index=True)
    shelf = db.Column(db.String, index=True)
    block = db.Column(db.String, index=True)
    writer = db.Column(db.String, index=True)
    loan = db.Column(db.String, index=True)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now
    )

search/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class BooksForm(FlaskForm):
    book_id = StringField(
        "고유번호",
        validators=[
            DataRequired(message="고유번호는 필수입니다."),
            Length(max=5, message="양식에 맞게 입력해주세요"),
        ],
    )
    bookname = StringField(
        "책 제목",
        validators=[
            DataRequired(message="책 제목은 필수입니다."),
            Length(max=30, message="30문자 이내로 입력해 주세요"),
        ],
    )
    shelf = StringField(
        "책장번호",
        validators=[
            DataRequired(message="책장번호 필수입니다."),
            Length(max=30, message="30문자 이내로 입력해 주세요"),
        ],
    )
    block = StringField(
        "블록",
        validators=[
            DataRequired(message="블록은 필수입니다."),
            Length(max=30, message="30문자 이내로 입력해 주세요"),
        ],
    )
    writer = StringField(
        "작가",

    )
    loan = StringField(
        "대출여부",        
        validators=[
            DataRequired(message="작가명은 필수입니다."),
            Length(max=30, message="30문자 이내로 입력해 주세요"),
        ],
    )

    submit = SubmitField("등록")

search/__init__.py
import project.search.models

search/views.py
from project.book import db
from project.search.models import Book
from project.search.forms import BooksForm
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

search = Blueprint(
    "search",
    __name__,
    template_folder="templates",
    static_folder="static"
)


# 예시
@search.route("/book")
def index():
    return render_template("search/create.html")


# 데이터베이스 열람
@search.route("/bookdb")
@login_required
def bookdb():
    books = Book.query.all()
    return render_template("search/index.html", books=books)


@search.route("/bookdb/new", methods=["GET", "POST"])
def create_book():
    # UserForm을 인스턴스화한다
    form2 = BooksForm()

    if form2.validate_on_submit():
        # 사용자를 작성한다
        book = Book(
            id=form2.book_id.data,
            bookname=form2.bookname.data,
            shelf=form2.shelf.data,
            block=form2.block.data,
            writer=form2.writer.data,
            loan=form2.loan.data,
        )

        # 사용자를 추가하고 커밋한다
        db.session.add(book)
        db.session.commit()

        # 사용자 데이터베이스 화면으로 리다이렉트한다
        return redirect(url_for("search.bookdb"))
    return render_template("search/create.html", form2=form2)


@search.route("/bookdb/<book_id>", methods=["GET", "POST"])
def edit_book(book_id):
    form = BooksForm()

    # User 모델을 이용하여 사용자를 취득한다
    book = Book.query.filter_by(id=book_id).first()

    # form으로부터 제출된 경우는 사용자를 갱신하여 사용자의 일람 화면으로 리다이렉트한다
    if form.validate_on_submit():
        book.id = form.book_id.data
        book.username = form.bookname.data
        book.shelf = form.shelf.data
        book.block = form.block.data
        book.writer = form.writer.data
        book.loan = form.loan.data
        db.session.add(book)
        db.session.commit()
        return redirect(url_for("search.bookdb"))

    # GET :  HTML을 반환
    return render_template("search/edit.html", book=book, form=form)


@search.route("/bookdb/<book_id>/delete", methods=["POST"])
@login_required
def delete_book(id):
    book = Book.query.filter_by(id=book_id).first()
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for("search.bookdb"))

search/templates/search/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />

    <title>{% block title %}{% endblock %}</title>
    <link href="static/{% block link %}{% endblock %}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('search.static',filename='style.css')}}" />
</head>

<body>

    {% block content %}{% endblock %}
</body>

</html>

search/templates/search/create.html
{% extends "search/base.html" %}
{% block title %}도서목록 작성{% endblock %}
{% block link %}create.css{% endblock %}
{% block content %}

<div>
    <h2>도서 목록 작성</h2>
    <form action="{{url_for('search.create_book')}}" method="POST" novalidate="novalidate">

        {{ form2.csrf_token }}

        <p>
            {{ form2.book_id.label }} {{ form2.book_id(placeholder="고유번호") }}
        </p>
        {% for error in form2.book_id.errors %}
        <span style="color : red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form2.bookname.label }} {{ form2.bookname(placeholder="사용자명") }}
        </p>
        {% for error in form2.bookname.errors %}
        <span style="color : red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form2.shelf.label }} {{ form2.shelf(placeholder="책장번호") }}
        </p>
        {% for error in form2.shelf.errors %}
        <span style="color : red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form2.block.label }} {{ form2.block(placeholder="블록번호") }}
        </p>
        {% for error in form2.block.errors %}
        <span style="color : red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form2.writer.label }} {{ form2.writer(placeholder="작가명") }}
        </p>
        {% for error in form2.writer.errors %}
        <span style="color : red;">{{ error }}</span>
        {% endfor %}

        <p>
            {{ form2.loan.label }} {{ form2.loan(placeholder="대출가능여부") }}
        </p>
        {% for error in form2.loan.errors %}
        <span style="color : red;">{{ error }}</span>
        {% endfor %}

        <p> {{ form2.submit(class="submit") }} </p>

    </form>
    {% endblock %}
</div>

search/templates/search/edit.html
{% extends "search/base.html" %}
{% block title %}도서 신규 작성{% endblock %}
{% block content %}

<h2>도서 편집</h2>
<form action="{{url_for('search.edit_book',book_id=book.id)}}" method="POST" novalidate="novalidate">

    {{ form.csrf_token }}

    <p>
        {{ form.book_id.label }} {{ form.book_id(placeholder="고유번호", value=book.book_id) }}
    </p>

    {% for error in form.book_id.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}


    <p>
        {{ form.bookname.label }} {{ form.bookname(placeholder="책제목", value=book.bookname) }}
    </p>

    {% for error in form.bookname.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.shelf.label }} {{ form.shelf(placeholder="책장번호", value=book.shelf) }}
    </p>

    {% for error in form.shelf.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.block.label }} {{ form.block(placeholder="블록번호", value=book.block) }}
    </p>

    {% for error in form.block.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.writer.label }} {{ form.writer(placeholder="작가명", value=book.writer) }}
    </p>

    {% for error in form.writer.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.loan.label }} {{ form.loan(placeholder="대출가능여부", value=book.loan) }}
    </p>

    {% for error in form.loan.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}



    <p><input type="submit" value="갱신" /> </p>
</form>

<form action="{{url_for('search.delete_book',book_id=book.id)}}" method="POST">
    {{form.csrf_token}}
    <input type="submit" value="삭제">
</form>

{% endblock %}

search/templates/search/index.html
{% extends "search/base.html" %}
{% block title %}도서목록{% endblock %}
{% block link %}index.css{% endblock %}
{% block content %}
<h2>도서목록</h2>

<div class="taga"><a href="{{url_for('search.create_book')}}">도서목록작성</a></div>
<table class="user">
    <tr class="category">
        <th>고유번호</th>
        <th>책 제목</th>
        <th>책장</th>
        <th>블록</th>
        <th>작가</th>
        <th>대출여부</th>
    </tr>
    {% for book in books %}

    <tr>
        <td>
            <a href="{{url_for('search.edit_book', book_id=book.id)}}">{{book.id}}</a>
        </td>
        <td>{{book.bookname}}</td>
        <td>{{book.shelf}}</td>
        <td>{{book.block}}</td>
        <td>{{book.writer}}</td>
        <td>{{book.loan}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}