crud/models.py
from datetime import datetime
from project.book import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now
    )

    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, Length


class UserForm(FlaskForm):
    user_id = StringField(
        "학번",
        validators=[
            DataRequired(message="학번은 필수입니다."),
            Length(max=10, message="학번양식에 맞게 입력해주세요"),
        ],
    )
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다."),
            Length(max=30, message="30문자 이내로 입력해 주세요"),
        ],
    )

    email = StringField(
        "메일 주소",
        validators=[
            DataRequired(message="메일 주소는 필수입니다."),
            Email(message="메일 주소의 형식으로 입력해주세요"),
        ],
    )

    password = PasswordField(
        "비밀번호",
        validators=[DataRequired(message="비밀번호는 필수입니다.")]
    )

    submit = SubmitField("신규등록")

crud/__init__.py
import project.crud.models

crud/views.py
# crud 앱의 엔드포인트
from project.crud.forms import UserForm         # 데이터베이스 가져오기
from flask import Blueprint, render_template, redirect, url_for
from project.book import db
from project.crud.models import User
from flask_login import login_required

# blueprint로 crud 앱 생성, 객체화
crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)


# 시작 페이지
@crud.route("/")
def start():
    return render_template("crud/start.html")


# 회원정보
@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)

# 회원정보 수정,읽기
@crud.route("/users/<user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()

    user = User.query.filter_by(id=user_id).first()     # User 모델을 이용하여 사용자를 취득한다

    # form으로부터 제출된 경우는 사용자를 갱신하여 사용자의 일람 화면으로 리다이렉트한다
    if form.validate_on_submit():
        user.id = form.user_id.data
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("crud.users"))

    return render_template("crud/edit.html", user=user, form=form)

# 회원정보 삭제
@crud.route("/users/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />

    <title>{% block title %}{% endblock %}</title>
    <link href="static/{% block link %}{% endblock %}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('crud.static', filename='style.css')}}" />
</head>

<body>
    <div>
        {% if current_user.is_authenticated %}
        <p>
            <span>{{current_user.username}}</span> -
            <span><a href="{{url_for('auth.logout') }}">로그아웃</a></span>
        </p>
        {% endif %}
    </div>

    {% block content %}{% endblock %}
</body>

</html>

crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}사용자 신규 작성{% endblock %}
{% block content %}


<h2>사용자 신규 작성</h2>

<form action="{{url_for('crud.create_user')}}" method="POST" novalidate="novalidate">

    {{ form.csrf_token }}

    <p>
        {{ form.user_id.label }} {{ form.user_id(placeholder="학번") }}
    </p>
    {% for error in form.user_id.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.username.label }} {{ form.username(placeholder="사용자명") }}
    </p>
    {% for error in form.username.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(placeholder="메일 주소") }}
    </p>
    {% for error in form.email.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.password.label }} {{ form.password(placeholder="비밀번호") }}
    </p>
    {% for error in form.password.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p> {{ form.submit() }} </p>

</form>
{% endblock %}

crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}사용자 신규 작성{% endblock %}
{% block content %}

<h2>사용자의 편집</h2>
<form action="{{url_for('crud.edit_user',user_id=user.id)}}" method="POST" novalidate="novalidate">

    {{ form.csrf_token }}

    <p>
        {{ form.user_id.label }} {{ form.user_id(placeholder="학번", value=user.user_id) }}
    </p>

    {% for error in form.user_id.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}


    <p>
        {{ form.username.label }} {{ form.username(placeholder="사용자명", value=user.username) }}
    </p>

    {% for error in form.username.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p>
        {{ form.email.label }} {{ form.email(placeholder="메일 주소", value=user.email) }}
    </p>

    {% for error in form.email.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}


    <p>
        {{ form.password.label }} {{ form.password(placeholder="비밀번호") }}
    </p>

    {% for error in form.password.errors %}
    <span style="color : red;">{{ error }}</span>
    {% endfor %}

    <p><input type="submit" value="갱신" /> </p>
</form>

<form action="{{url_for('crud.delete_user',user_id=user.id)}}" method="POST">
    {{form.csrf_token}}
    <input type="submit" value="삭제">
</form>
{% endblock %}

crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}회원관리{% endblock %}
{% block link %}index.css{% endblock %}
{% block content %}
<div>
    <h2>회원 관리</h2>

    <div class="taga"> <a href="{{url_for('auth.signup')}}">사용자 신규등록(관리자용)</a></div>
    <table class="user">
        <tr class="category">
            <th>학번</th>
            <th>사용자명</th>
            <th>메일 주소</th>
        </tr>
        {% for user in users %}

        <tr>
            <td>
                <div class="tagb"> <a href="{{url_for('crud.edit_user', user_id=user.id)}}">{{user.id}}</a></div>
            </td>
            <td>{{user.username}}</td>
            <td>{{user.email}}</td>
        </tr>
        {% endfor %}
    </table>

    {% endblock %}
</div>

crud/templates/crud/start.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8" />
    <link href="static/start.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <title>ㅇㅇ대학교 도서관</title>
</head>

<body>
    <section>

        <div>
            <h1 class="animate__animated animate__fadeIn animate__slower">책에 집중하라, Book-Focusing<h1>
                    <h2 class="animate__animated animate__fadeIn animate__slower animate__delay-2s">ㅇㅇ대학교 도서관에 오신 걸
                        환영합니다
                    </h2>
        </div>
        <div id="block">
            <div class="taga"> <a href="{{url_for('auth.signup')}}">회원가입창으로 가기</a></div>

            <div class="tagb"> <a href="{{url_for('auth.login')}}">로그인창으로 가기</a></div>
        </div>

    </section>
</body>

</html>